### ISSUE TITLE
Error with the form at https://bnjis.github.io/Facebook-permanent-token-generator/

### ISSUE THREAD

**Issue by emeagenciadigital** [Bnjis/Facebook-permanent-token-generator#14]
So i fill all the fields and press SUBMIT but nothing happens. If i open the console i get this messages:

Uncaught (in promise) TypeError: Cannot read property 'data' of undefined
    at Form.js:83
Form.js:82 TypeError: Cannot read property 'access_token' of undefined
    at Form.js:78

**Comment by Bnjis** [comment]
This is resolved
